---
name: Liberty City
on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  Zip:
    runs-on: ubuntu-latest
    steps:

      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v4
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-swapfile: 'true'
       
      - name: Create Zip
        run: |
          curl -L -O https://nightly.link/AdityaGarg8/random/actions/runs/12803481210/Liberty%20City%20Preservation%20Project%20-%20FiveM.zip
          #unzip -d sketchy Sketchy.zip
          tree

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: "Sketchy"
          path: ${{ github.workspace }}/sketchy/sketchy.tar.gz
